//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 04:53:41 PM IST 
//


package com.nia.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fcopy_source_prop complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fcopy_source_prop">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="s_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="s_fname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="del_source_file" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fcopy_source_prop", propOrder = {
    "sPath",
    "sFname",
    "delSourceFile",
    "retryAttempts"
})
public class FcopySourceProp {

    @XmlElement(name = "s_path", required = true)
    protected String sPath;
    @XmlElement(name = "s_fname", required = true)
    protected String sFname;
    @XmlElement(name = "del_source_file")
    protected boolean delSourceFile;
    @XmlElement(name="retry_attempts", required=true)
    protected int retryAttempts;
    /**
     * Gets the value of the sPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPath() {
        return sPath;
    }

    /**
     * Sets the value of the sPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPath(String value) {
        this.sPath = value;
    }

    /**
     * Gets the value of the sFname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSFname() {
        return sFname;
    }

    /**
     * Sets the value of the sFname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSFname(String value) {
        this.sFname = value;
    }

    /**
     * Gets the value of the delSourceFile property.
     * 
     */
    public boolean isDelSourceFile() {
        return delSourceFile;
    }

    /**
     * Sets the value of the delSourceFile property.
     * 
     */
    public void setDelSourceFile(boolean value) {
        this.delSourceFile = value;
    }

	public int getRetryAttempts() {
		return retryAttempts;
	}

	public void setRetryAttempts(int retryAttempts) {
		this.retryAttempts = retryAttempts;
	}

}
