/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nia.jpa.dao;

import java.sql.Connection;

import com.nia.jpa.dto.Sftp_fname_dto;
import com.nia.jpa.exception.Sftp_fname_dao_Exception;


public interface Sftp_fname_dao
{
	
	/** 
	 * Returns all rows from the of_monitoring table that match the criteria ''.
	 */
//	public Sftp_fname_dto findAll(Connection conn) throws Sftp_fname_dao_Exception;

	public Sftp_fname_dto findAll(Connection conn,String officeCode, String sourceName, String bankName) throws Sftp_fname_dao_Exception;
	
	/** 
	 * Returns all rows from the of_monitoring table that match the criteria 'programe = :programe'.
	 */
	//public List<Of_monitor_dto> findWhereProgrameEquals(Connection conn, String programe) throws OfMonitoringDaoException;

	
	
}
