//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 04:53:41 PM IST 
//


package com.nia.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fcopy_source_prop complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fcopy_source_prop">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="s_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="s_fname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="del_source_file" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="f_limits" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_newExtension" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_KeyStoreFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_keyStorePwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_bank" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_merchantcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_remitterAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>    
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fcopy_source_prop", propOrder = {
    "sPath",
    "sFname",
    "delSourceFile",
    "retryAttempts",
    "recordsLimit",
    "newExtension",
    "keyStoredFile",
    "keyStoredPwd",
    "bank",
    "merchnatcode",
    "remitterAccountNumber"
})
public class FcopySourceProp {

    @XmlElement(name = "s_path", required = true)
    protected String sPath;
    @XmlElement(name = "s_fname", required = true)
    protected String sFname;
    @XmlElement(name = "del_source_file")
    protected boolean delSourceFile;
    @XmlElement(name="retry_attempts", required=true)
    protected int retryAttempts;
    
    @XmlElement(name = "f_limits", required = true)
    protected String recordsLimit;
    @XmlElement(name = "f_newExtension", required = true)
    protected String newExtension;
    @XmlElement(name = "f_KeyStoreFile", required = true)
    protected String keyStoredFile;
    @XmlElement(name = "f_keyStorePwd", required = true)
    protected String keyStoredPwd;
    @XmlElement(name = "f_bank", required = true)
    protected String bank;
    @XmlElement(name = "f_merchantcode", required = true)
    protected String merchnatcode;
    @XmlElement(name = "f_remitterAccountNumber", required = true)
    protected String remitterAccountNumber;
    
    
    
    
    /**
     * Gets the value of the sPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPath() {
        return sPath;
    }

    /**
     * Sets the value of the sPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPath(String value) {
        this.sPath = value;
    }

    /**
     * Gets the value of the sFname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSFname() {
        return sFname;
    }

    /**
     * Sets the value of the sFname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSFname(String value) {
        this.sFname = value;
    }

    /**
     * Gets the value of the delSourceFile property.
     * 
     */
    public boolean isDelSourceFile() {
        return delSourceFile;
    }

    /**
     * Sets the value of the delSourceFile property.
     * 
     */
    public void setDelSourceFile(boolean value) {
        this.delSourceFile = value;
    }

	public int getRetryAttempts() {
		return retryAttempts;
	}

	public void setRetryAttempts(int retryAttempts) {
		this.retryAttempts = retryAttempts;
	}
   
	/**
	 * @return the recordsLimit
	 */
	public String getRecordsLimit() {
		return recordsLimit;
	}
	/**
	 * @param recordsLimit the recordsLimit to set
	 */
	public void setRecordsLimit(String recordsLimit) {
		this.recordsLimit = recordsLimit;
	}
	public String getNewExtension() {
		return newExtension;
	}
	/**
	 * @param newExtension the newExtension to set
	 */
	public void setNewExtension(String newExtension) {
		this.newExtension = newExtension;
	}

	/**
	 * @return the sPath
	 */
	public String getsPath() {
		return sPath;
	}

	/**
	 * @param sPath the sPath to set
	 */
	public void setsPath(String sPath) {
		this.sPath = sPath;
	}

	/**
	 * @return the sFname
	 */
	public String getsFname() {
		return sFname;
	}

	/**
	 * @param sFname the sFname to set
	 */
	public void setsFname(String sFname) {
		this.sFname = sFname;
	}

	/**
	 * @return the keyStoredFile
	 */
	public String getKeyStoredFile() {
		return keyStoredFile;
	}

	/**
	 * @param keyStoredFile the keyStoredFile to set
	 */
	public void setKeyStoredFile(String keyStoredFile) {
		this.keyStoredFile = keyStoredFile;
	}

	/**
	 * @return the keyStoredPwd
	 */
	public String getKeyStoredPwd() {
		return keyStoredPwd;
	}

	/**
	 * @param keyStoredPwd the keyStoredPwd to set
	 */
	public void setKeyStoredPwd(String keyStoredPwd) {
		this.keyStoredPwd = keyStoredPwd;
	}

	/**
	 * @return the bank
	 */
	public String getBank() {
		return bank;
	}

	/**
	 * @param bank the bank to set
	 */
	public void setBank(String bank) {
		this.bank = bank;
	}

	/**
	 * @return the merchnatcode
	 */
	public String getMerchnatcode() {
		return merchnatcode;
	}

	/**
	 * @param merchnatcode the merchnatcode to set
	 */
	public void setMerchnatcode(String merchnatcode) {
		this.merchnatcode = merchnatcode;
	}

	/**
	 * @return the remitterAccountNumber
	 */
	public String getRemitterAccountNumber() {
		return remitterAccountNumber;
	}

	/**
	 * @param remitterAccountNumber the remitterAccountNumber to set
	 */
	public void setRemitterAccountNumber(String remitterAccountNumber) {
		this.remitterAccountNumber = remitterAccountNumber;
	}
    
    
}
