//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 04:53:41 PM IST 
//


package com.nia.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for f_splitProperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="f_splitProperty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="driver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="server_ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="schema_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "f_splitProperty", propOrder = {
    "recordsLimit",
    "processdLocation",
    "tempfolderLocation",
    "merchantCode",
    "newExtension"
})
public class fsplitProperty {

	    @XmlElement(name = "f_limits", required = true)
	    protected String recordsLimit;
	    @XmlElement(name = "f_Processd", required = true)
	    protected String processdLocation;
	    @XmlElement(name = "f_tempfolder", required = true)
	    protected String tempfolderLocation;
	    @XmlElement(name = "f_MerchantCode", required = true)
	    protected String merchantCode;
	    @XmlElement(name = "f_newExtension", required = true)
	    protected String newExtension;
		/**
		 * @return the recordsLimit
		 */
		public String getRecordsLimit() {
			return recordsLimit;
		}
		/**
		 * @param recordsLimit the recordsLimit to set
		 */
		public void setRecordsLimit(String recordsLimit) {
			this.recordsLimit = recordsLimit;
		}
		/**
		 * @return the processdLocation
		 */
		public String getProcessdLocation() {
			return processdLocation;
		}
		/**
		 * @param processdLocation the processdLocation to set
		 */
		public void setProcessdLocation(String processdLocation) {
			this.processdLocation = processdLocation;
		}
		/**
		 * @return the tempfolderLocation
		 */
		public String getTempfolderLocation() {
			return tempfolderLocation;
		}
		/**
		 * @param tempfolderLocation the tempfolderLocation to set
		 */
		public void setTempfolderLocation(String tempfolderLocation) {
			this.tempfolderLocation = tempfolderLocation;
		}
		/**
		 * @return the merchantCode
		 */
		public String getMerchantCode() {
			return merchantCode;
		}
		/**
		 * @param merchantCode the merchantCode to set
		 */
		public void setMerchantCode(String merchantCode) {
			this.merchantCode = merchantCode;
		}
		/**
		 * @return the newExtension
		 */
		public String getNewExtension() {
			return newExtension;
		}
		/**
		 * @param newExtension the newExtension to set
		 */
		public void setNewExtension(String newExtension) {
			this.newExtension = newExtension;
		}
	    
	    

   
}
