//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 04:53:41 PM IST 
//


package com.nia.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nia.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("http://www.example.org/config_schema", "config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nia.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link DbProperty }
     * 
     */
    public DbProperty createDbProperty() {
        return new DbProperty();
    }
    
  /*  public fsplitProperty createfsplitProperty() {
        return new fsplitProperty();
    }
    */
    /**
     * Create an instance of {@link FilecopyProperty }
     * 
     */
    public FilecopyProperty createFilecopyProperty() {
        return new FilecopyProperty();
    }

    /**
     * Create an instance of {@link FcopyTargetProp }
     * 
     */
    public FcopyTargetProp createFcopyTargetProp() {
        return new FcopyTargetProp();
    }

    /**
     * Create an instance of {@link FcopySourceProp }
     * 
     */
    public FcopySourceProp createFcopySourceProp() {
        return new FcopySourceProp();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Config }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/config_schema", name = "config")
    public JAXBElement<Config> createConfig(Config value) {
        return new JAXBElement<Config>(_Config_QNAME, Config.class, null, value);
    }

}
