/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nia.jpa.dao;

import java.sql.Connection;
import java.util.List;

import com.nia.jpa.dto.*;
import com.nia.jpa.exception.OfMonitoringDaoException;
import com.nia.jpa.exception.ReverseFeedDaoException;


public interface ReverseFeedDao
{
	
	/** 
	 * Returns all rows from the of_monitoring table that match the criteria ''.
	 */
	public List<Reverse_Feed_dto> findAll(Connection conn) throws ReverseFeedDaoException;

	
	/** 
	 * Returns all rows from the of_monitoring table that match the criteria 'programe = :programe'.
	 */
	
	
	
	//public List<Of_monitor_dto> findWhereProgrameEquals(Connection conn, String programe) throws OfMonitoringDaoException;

	
	
}
