//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.20 at 12:01:59 PM IST 
//


package com.nia.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for config complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="email_prop" type="{http://www.example.org/config_schema}email_prop"/>
 *         &lt;element name="fcopy_prop" type="{http://www.example.org/config_schema}filecopy_property" maxOccurs="unbounded"/>
 *         &lt;element name="fdecrypt_prop" type="{http://www.example.org/config_schema}filedecrypt_prop"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "config", propOrder = {
    "emailProp",
    "fcopyProp",
    "fdecryptProp"
})
public class Config {

    @XmlElement(name = "email_prop", required = true)
    protected EmailProp emailProp;
    @XmlElement(name = "fcopy_prop", required = true)
    protected List<FilecopyProperty> fcopyProp;
    @XmlElement(name = "fdecrypt_prop", required = true)
    protected FiledecryptProp fdecryptProp;

    /**
     * Gets the value of the emailProp property.
     * 
     * @return
     *     possible object is
     *     {@link EmailProp }
     *     
     */
    public EmailProp getEmailProp() {
        return emailProp;
    }

    /**
     * Sets the value of the emailProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailProp }
     *     
     */
    public void setEmailProp(EmailProp value) {
        this.emailProp = value;
    }

    /**
     * Gets the value of the fcopyProp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fcopyProp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFcopyProp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilecopyProperty }
     * 
     * 
     */
    public List<FilecopyProperty> getFcopyProp() {
        if (fcopyProp == null) {
            fcopyProp = new ArrayList<FilecopyProperty>();
        }
        return this.fcopyProp;
    }

    /**
     * Gets the value of the fdecryptProp property.
     * 
     * @return
     *     possible object is
     *     {@link FiledecryptProp }
     *     
     */
    public FiledecryptProp getFdecryptProp() {
        return fdecryptProp;
    }

    /**
     * Sets the value of the fdecryptProp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiledecryptProp }
     *     
     */
    public void setFdecryptProp(FiledecryptProp value) {
        this.fdecryptProp = value;
    }

}
