//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.20 at 12:01:59 PM IST 
//


package com.nia.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fcopy_source_prop complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fcopy_source_prop">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="s_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="s_fname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="s_ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="s_port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="s_username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="s_password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="del_source_file" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="s_prefix" type="{http://www.example.org/config_schema}f_identifier" maxOccurs="unbounded"/>
 *         &lt;element name="retry_attempts" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fcopy_source_prop", propOrder = {
    "sPath",
    "sFname",
    "sIp",
    "sPort",
    "sUsername",
    "sPassword",
    "delSourceFile",
    "sPrefix",
    "retryAttempts"
})
public class FcopySourceProp {

    @XmlElement(name = "s_path", required = true)
    protected String sPath;
    @XmlElement(name = "s_fname", required = true)
    protected String sFname;
    @XmlElement(name = "s_ip", required = true)
    protected String sIp;
    @XmlElement(name = "s_port")
    protected int sPort;
    @XmlElement(name = "s_username", required = true)
    protected String sUsername;
    @XmlElement(name = "s_password", required = true)
    protected String sPassword;
    @XmlElement(name = "del_source_file")
    protected boolean delSourceFile;
    @XmlElement(name = "s_prefix", required = true)
    protected List<FIdentifier> sPrefix;
    @XmlElement(name = "retry_attempts")
    protected int retryAttempts;

    /**
     * Gets the value of the sPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPath() {
        return sPath;
    }

    /**
     * Sets the value of the sPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPath(String value) {
        this.sPath = value;
    }

    /**
     * Gets the value of the sFname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSFname() {
        return sFname;
    }

    /**
     * Sets the value of the sFname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSFname(String value) {
        this.sFname = value;
    }

    /**
     * Gets the value of the sIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIp() {
        return sIp;
    }

    /**
     * Sets the value of the sIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIp(String value) {
        this.sIp = value;
    }

    /**
     * Gets the value of the sPort property.
     * 
     */
    public int getSPort() {
        return sPort;
    }

    /**
     * Sets the value of the sPort property.
     * 
     */
    public void setSPort(int value) {
        this.sPort = value;
    }

    /**
     * Gets the value of the sUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUsername() {
        return sUsername;
    }

    /**
     * Sets the value of the sUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUsername(String value) {
        this.sUsername = value;
    }

    /**
     * Gets the value of the sPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPassword() {
        return sPassword;
    }

    /**
     * Sets the value of the sPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPassword(String value) {
        this.sPassword = value;
    }

    /**
     * Gets the value of the delSourceFile property.
     * 
     */
    public boolean isDelSourceFile() {
        return delSourceFile;
    }

    /**
     * Sets the value of the delSourceFile property.
     * 
     */
    public void setDelSourceFile(boolean value) {
        this.delSourceFile = value;
    }

    /**
     * Gets the value of the sPrefix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sPrefix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSPrefix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FIdentifier }
     * 
     * 
     */
    public List<FIdentifier> getSPrefix() {
        if (sPrefix == null) {
            sPrefix = new ArrayList<FIdentifier>();
        }
        return this.sPrefix;
    }

    /**
     * Gets the value of the retryAttempts property.
     * 
     */
    public int getRetryAttempts() {
        return retryAttempts;
    }

    /**
     * Sets the value of the retryAttempts property.
     * 
     */
    public void setRetryAttempts(int value) {
        this.retryAttempts = value;
    }

}
