//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.20 at 12:01:59 PM IST 
//


package com.nia.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for f_identifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="f_identifier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="f_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="f_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "f_identifier", propOrder = {
    "fType",
    "fPrefix"
})
public class FIdentifier {

    @XmlElement(name = "f_type", required = true)
    protected String fType;
    @XmlElement(name = "f_prefix", required = true)
    protected String fPrefix;

    /**
     * Gets the value of the fType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFType() {
        return fType;
    }

    /**
     * Sets the value of the fType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFType(String value) {
        this.fType = value;
    }

    /**
     * Gets the value of the fPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPrefix() {
        return fPrefix;
    }

    /**
     * Sets the value of the fPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPrefix(String value) {
        this.fPrefix = value;
    }

}
