//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.20 at 12:01:59 PM IST 
//


package com.nia.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for filedecrypt_prop complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filedecrypt_prop">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shFile_Path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plainFile_Path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plainFileBackup_Path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encryptedFile_Path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encryptedFileBackup_Path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inputFile_Path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filedecrypt_prop", propOrder = {
    "shFilePath",
    "plainFilePath",
    "plainFileBackupPath",
    "encryptedFilePath",
    "encryptedFileBackupPath",
    "inputFilePath"
})
public class FiledecryptProp {

    @XmlElement(name = "shFile_Path", required = true)
    protected String shFilePath;
    @XmlElement(name = "plainFile_Path", required = true)
    protected String plainFilePath;
    @XmlElement(name = "plainFileBackup_Path", required = true)
    protected String plainFileBackupPath;
    @XmlElement(name = "encryptedFile_Path", required = true)
    protected String encryptedFilePath;
    @XmlElement(name = "encryptedFileBackup_Path", required = true)
    protected String encryptedFileBackupPath;
    @XmlElement(name = "inputFile_Path", required = true)
    protected String inputFilePath;

    /**
     * Gets the value of the shFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShFilePath() {
        return shFilePath;
    }

    /**
     * Sets the value of the shFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShFilePath(String value) {
        this.shFilePath = value;
    }

    /**
     * Gets the value of the plainFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlainFilePath() {
        return plainFilePath;
    }

    /**
     * Sets the value of the plainFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlainFilePath(String value) {
        this.plainFilePath = value;
    }

    /**
     * Gets the value of the plainFileBackupPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlainFileBackupPath() {
        return plainFileBackupPath;
    }

    /**
     * Sets the value of the plainFileBackupPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlainFileBackupPath(String value) {
        this.plainFileBackupPath = value;
    }

    /**
     * Gets the value of the encryptedFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptedFilePath() {
        return encryptedFilePath;
    }

    /**
     * Sets the value of the encryptedFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedFilePath(String value) {
        this.encryptedFilePath = value;
    }

    /**
     * Gets the value of the encryptedFileBackupPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptedFileBackupPath() {
        return encryptedFileBackupPath;
    }

    /**
     * Sets the value of the encryptedFileBackupPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedFileBackupPath(String value) {
        this.encryptedFileBackupPath = value;
    }

    /**
     * Gets the value of the inputFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputFilePath() {
        return inputFilePath;
    }

    /**
     * Sets the value of the inputFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputFilePath(String value) {
        this.inputFilePath = value;
    }

}
