//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.20 at 12:01:59 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/config_schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nia.jaxb;
