/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nia.jpa.dto;

import java.io.Serializable;

public class Sftp_fname_dto implements Serializable
{
	/**
	 * 
	 */
	
	protected String file_name;
		
	public Sftp_fname_dto()
	{
	}

	
	public String getFile_name() {
		return file_name;
	}





	public void setFile_name(String file_name) {
		this.file_name = file_name;
	}





	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Sftp_fname_dto)) {
			return false;
		}
		
		final Sftp_fname_dto _cast = (Sftp_fname_dto) _other;
		if (file_name == null ? _cast.file_name != file_name : !file_name.equals( _cast.file_name )) {
			return false;
		}
					
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		
		
	
		if (file_name != null) {
			_hashCode = 29 * _hashCode + file_name.hashCode();
		}
		
		_hashCode = 29 * _hashCode;
		return _hashCode;
	}

	

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nia.jpa.dto.sftp_fname_dto: " );
		ret.append( "file_name=" + file_name );
		
		return ret.toString();
	}

}
