/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.nia.jpa.dto;

import java.io.Serializable;

public class Of_monitor_dto implements Serializable
{
	protected String request_id;
	protected String programe;
	protected String phaseCode;
	protected String statusCode;
	protected String arg_txt;
	protected String req_startTime;
	protected String act_startTime;
	protected String finishTime;
	protected String runTime;
		
	public Of_monitor_dto()
	{
	}

	
	
	public String getRequest_id() {
		return request_id;
	}


	public void setRequest_id(String request_id) {
		this.request_id = request_id;
	}





	/**
	 * Method 'getPrograme'
	 * 
	 * @return String
	 */
	public String getPrograme()
	{
		return programe;
	}

	/**
	 * Method 'setPrograme'
	 * 
	 * @param programe
	 */
	public void setPrograme(String programe)
	{
		this.programe = programe;
	}

	/**
	 * Method 'getPhaseCode'
	 * 
	 * @return String
	 */
	public String getPhaseCode()
	{
		return phaseCode;
	}

	/**
	 * Method 'setPhaseCode'
	 * 
	 * @param phaseCode
	 */
	public void setPhaseCode(String phaseCode)
	{
		this.phaseCode = phaseCode;
	}

	/**
	 * Method 'getStatusCode'
	 * 
	 * @return String
	 */
	public String getStatusCode()
	{
		return statusCode;
	}

	/**
	 * Method 'setStatusCode'
	 * 
	 * @param statusCode
	 */
	public void setStatusCode(String statusCode)
	{
		this.statusCode = statusCode;
	}

	
	/**
	 * Method 'getFinishTime'
	 * 
	 * @return String
	 */
	public String getFinishTime()
	{
		return finishTime;
	}

	/**
	 * Method 'setFinishTime'
	 * 
	 * @param finishTime
	 */
	public void setFinishTime(String finishTime)
	{
		this.finishTime = finishTime;
	}

	/**
	 * Method 'getRunTime'
	 * 
	 * @return String
	 */
	public String getRunTime()
	{
		return runTime;
	}

	/**
	 * Method 'setRunTime'
	 * 
	 * @param runTime
	 */
	public void setRunTime(String runTime)
	{
		this.runTime = runTime;
	}

	
	
	public String getArg_txt() {
		return arg_txt;
	}

	public void setArg_txt(String arg_txt) {
		this.arg_txt = arg_txt;
	}

	
	
	
	public String getReq_startTime() {
		return req_startTime;
	}

	public void setReq_startTime(String req_startTime) {
		this.req_startTime = req_startTime;
	}

	public String getAct_startTime() {
		return act_startTime;
	}

	public void setAct_startTime(String act_startTime) {
		this.act_startTime = act_startTime;
	}


	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Of_monitor_dto)) {
			return false;
		}
		
		final Of_monitor_dto _cast = (Of_monitor_dto) _other;
		if (request_id == null ? _cast.request_id != request_id : !request_id.equals( _cast.request_id )) {
			return false;
		}
	
		
		if (programe == null ? _cast.programe != programe : !programe.equals( _cast.programe )) {
			return false;
		}
		
		if (phaseCode == null ? _cast.phaseCode != phaseCode : !phaseCode.equals( _cast.phaseCode )) {
			return false;
		}
		
		if (statusCode == null ? _cast.statusCode != statusCode : !statusCode.equals( _cast.statusCode )) {
			return false;
		}
		
		if (req_startTime == null ? _cast.req_startTime != req_startTime : !req_startTime.equals( _cast.req_startTime )) {
			return false;
		}
		if (act_startTime == null ? _cast.act_startTime != act_startTime : !act_startTime.equals( _cast.act_startTime )) {
			return false;
		}
		
		if (finishTime == null ? _cast.finishTime != finishTime : !finishTime.equals( _cast.finishTime )) {
			return false;
		}
		
		if (runTime == null ? _cast.runTime != runTime : !runTime.equals( _cast.runTime )) {
			return false;
		}
		
		if (arg_txt == null ? _cast.arg_txt != arg_txt : !arg_txt.equals( _cast.arg_txt )) {
			return false;
		}
		
			
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		
		
	
		if (request_id != null) {
			_hashCode = 29 * _hashCode + request_id.hashCode();
		}
		
		if (programe != null) {
			_hashCode = 29 * _hashCode + programe.hashCode();
		}
		
		if (phaseCode != null) {
			_hashCode = 29 * _hashCode + phaseCode.hashCode();
		}
		
		if (statusCode != null) {
			_hashCode = 29 * _hashCode + statusCode.hashCode();
		}
		

		if (req_startTime != null) {
			_hashCode = 29 * _hashCode + req_startTime.hashCode();
		}
		
		
		if (act_startTime != null) {
			_hashCode = 29 * _hashCode + act_startTime.hashCode();
		}
		
		if (finishTime != null) {
			_hashCode = 29 * _hashCode + finishTime.hashCode();
		}
		
		if (runTime != null) {
			_hashCode = 29 * _hashCode + runTime.hashCode();
		}
	
		if (arg_txt != null) {
			_hashCode = 29 * _hashCode + arg_txt.hashCode();
		}
			
		_hashCode = 29 * _hashCode;
		return _hashCode;
	}

	

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.nia.jpa.dto.OfMonitoring: " );
		ret.append( "programe=" + programe );
		ret.append( ", phaseCode=" + phaseCode );
		ret.append( ", statusCode=" + statusCode );
		ret.append( ", req_startTime=" + req_startTime );
		ret.append( ", act_startTime=" + act_startTime );
		ret.append( ", finishTime=" + finishTime );
		ret.append( ", runTime=" + runTime );
		ret.append( ", arg_txt=" + arg_txt );
		
		return ret.toString();
	}

}
